### PR TITLE
Remove BlazeLayout dependency

### PR DESCRIPTION
**Pull request by imajus**
@denihs kindly merge this one
@dr-dimitru has approved it

### CODE REVIEW

**Review by dr-dimitru — APPROVED** [review]

**Comment by dr-dimitru** [comment]
@filipenevola @harryadel is there a way to escalate this one?

**Comment by filipenevola** [comment]
hey @dr-dimitru I created this org here on GitHub but I don't have write permissions anymore.

So I can't help but I'll ping the core team in pvt as well.

**Review by denihs — APPROVED** [review]

**Comment by denihs** [comment]
There you go! Sorry I didn't see this before.

**Comment by dr-dimitru** [comment]
@denihs thank you, would you release its update?

**Comment by denihs** [comment]
Hi! Version 1.1.0 [published](https://packosphere.com/useraccounts/flow-routing-extra)

**Comment by imajus** [comment]
@denihs could you also merge [this](https://github.com/meteor-compat/useraccounts-core/pull/10) one?

**Comment by ricaragao** [comment]
@imajus , Any other reason to remove blaze-layout other than it being out of date? I ran into a problem in my scenario that I only resolved by adding an updated blaze-layout, pwix:blaze-layout. If that's all, I'd like to revert it.

**Comment by imajus** [comment]
@ricaragao this package doesn't use BlazeLayout directly so it was just a stale dependency. By removing it I fixed an issue which I had with my project which didn't need BlazeLayout dependency but it was installed automatically with this package causing version conflicts.

**Pull request merged**
